<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'LocalTransfer.Mobile'">
    <BaseIntermediateOutputPath>$([System.IO.Path]::GetTempPath())LocalTransferBuild/$(MSBuildProjectName)/obj/</BaseIntermediateOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj/**;bin/**</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
  </PropertyGroup>
</Project>
